#! /bin/sh
# /etc/init.d/start_receive

### BEGIN INIT INFO
# Provides:          receive
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Simple script to start a program at boot
# Description:       A simple script from www.stuffaboutcode.com which will start / stop a program a boot / shutdown.
### END INIT INFO

# If you want a command to always run, put it here

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting receiving"
    # run application you want to start
    nohup python3 -u /home/pi/heatseek/receive.py 2> /dev/null >> /home/pi/heatseek/data/readings.tsv  &
    ;;
  stop)
    echo "Stopping receiving"
    # kill application you want to stop
    killall receive
    ;;
  *)
    echo "Usage: /etc/init.d/start_receive {start|stop}"
    exit 1
    ;;
esac

exit 0
